#!/bin/sh
# Called by "git push" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.

node common/scripts/install-run-rush.js change --verify || exit $?
