name: Check Build and Test
on:
  pull_request:
    branches:
      - main

env:
  NODE_VERSION: 18.x

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Setup Node Version ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install PNPM
        run: npm install -g pnpm
      - name: Install RushJS
        run: npm install -g @microsoft/rush
      - name: Verify Change Logs
        run: rush change --verify
      - name: Verify each project's package.json
        run: rush check
      - name: Install Dependencies
        run: rush update
      - name: Build Packages
        run: rush rebuild --verbose
      - name: Rush Purge
        continue-on-error: true
        run: rush purge
      - name: Install E2E Tester
        working-directory: ./e2e
        run: pnpm i
      - name: Install Examples Dependencies
        working-directory: ./e2e
        run: pnpm ex:install
      - name: Build Examples
        working-directory: ./e2e
        run: pnpm ex:build
      - name: Test E2E
        working-directory: ./e2e
        run: pnpm test:headless
      - name: Upload Playwright Report
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: playwright-report
          path: ./e2e/playwright-report/
          retention-days: 1
